spring:
  application:
    name: ylt-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhe194/ylt_cloud_config
          username: xingpengcheng
          password: xingpengcheng123
  rabbitmq:
    username: guest
    password: guest
    host: 119.3.48.53
    port: 5672
  security:
    user:
      name: qdsg
      password: qdsg2018
  zipkin:
    base-url: http://master.qdsgvision.com:9411/
  sleuth:
    sampler:
      probability: 0.2

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@master.qdsgvision.com:8761/eureka,http://${spring.security.user.name}:${spring.security.user.password}@backup.qdsgvision.com:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: 119.3.48.53:${server.port}
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

